# Spring Boot configuration
spring:
  # Database
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trello
    username: trello
    password: trello
  # FlyWay
  flyway:
     baseline-on-migrate: true
     locations:
              - classpath:migrationsForDB
     url: jdbc:postgresql://localhost:5432/trello
     username: trello
     password: trello

  # Liquibase
  liquibase:
    enabled: false




