# Spring Boot configuration
location: src/main/resources/downloads
spring:
  # Database
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/trello
    username: trello
    password: trello

  flyway:
    enabled: false
    validate-on-migrate: true

  # Liquibase
  liquibase:
    enabled: false
  jpa:
    hibernate:
        ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    properties:
          javax:
            persistence:
              validation:
                mode: auto
          hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
              lob:
                non_contextual_creation: false
    database: postgresql
    open-in-view: false
    generate-ddl: false

  mvc:
    pathmatch:
     matching-strategy: ant_path_matcher


server:
  port: 8082
  error:
    include-message: always
    include-exception: true