CREATE TYPE workspace_visibility AS ENUM('PUBLIC', 'PRIVATE');
CREATE TYPE board_visibility AS ENUM('PUBLIC', 'PRIVATE', 'WORKSPACE');
CREATE TYPE user_role AS ENUM('GUEST', 'MEMBER', 'ADMIN');
CREATE TYPE color as ENUM( 'NULL', 'RED','GREEN','YELLOW','BLACK','BLUE','VIOLET','ORANGE')
